[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
decentra_jockey = "2VAeYBq2nVs7Xqsm1KqtUQJgtNURKWRMigAGZnb8N32c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/marcodotio/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
